#!/bin/bash

# HAVE TO RUNAS SOURCE 
# source ./fast-find 

# launches fast find, allows for cd
touch ~/.fftmp # creates temp file
eval "./exec $@" # runs the command
cd_to="$(cat ~/.fftmp)"

if [ -f "$cd_to" ]
then
    cd "$(dirname $cd_to)"
else if [ -d "$cd_to" ]
then
    cd "$cd_to"
fi
# if the user didnt want to cd, nothing will happen

rm ~/.fftmp # remove temp file